from django.db import models

# Create your models here.
class Stop(models.Model):
    AgencyCode = models.TextField()
    AgencyName = models.CharField(max_length=100,null=True)
    DateOfStop = models.DateField(null=True)
    TimeOfStop = models.TimeField(null=True)
    DurationOfStop = models.CharField(max_length=99,null=True) # minutes?
    zipcode = models.CharField(max_length=100,null=True)
    VehicleMake = models.TextField(null=True)
    VehicleYear = models.CharField(max_length=99,null=True)
    DriversYearofBirth = models.CharField(max_length=99,null=True)
    DriverSex = models.CharField(max_length=99,null=True)
    DriverRace = models.CharField(max_length=99,null=True)
    ReasonForStop = models.CharField(max_length=99,null=True)
    TypeOfMovingViolation = models.CharField(max_length=10,null=True)
    ResultOfStop = models.CharField(max_length=99,null=True)
    BeatLocationOfStop = models.TextField(null=True)
    VehicleConsentSearchRequested  = models.CharField(max_length=99,null=True)
    VehicleConsentGiven  = models.CharField(max_length=99,null=True)
    VehicleSearchConducted  = models.CharField(max_length=99,null=True)
    VehicleSearchConductedBy  = models.CharField(max_length=99,null=True)
    VehicleContrabandFound  = models.CharField(max_length=99,null=True)
    VehicleDrugsFound  = models.CharField(max_length=99,null=True)
    VehicleDrugParaphernaliaFound  = models.CharField(max_length=99,null=True)
    VehicleAlcoholFound  = models.CharField(max_length=99,null=True)
    VehicleWeaponFound  = models.CharField(max_length=99,null=True)
    VehicleStolenPropertyFound  = models.CharField(max_length=99,null=True)
    VehicleOtherContrabandFound  = models.CharField(max_length=99,null=True)
    VehicleDrugAmount  = models.CharField(max_length=99,null=True)
    DriverConsentSearchRequested  = models.CharField(max_length=99,null=True)
    DriverConsentGiven  = models.CharField(max_length=99,null=True)
    DriverSearchConducted  = models.CharField(max_length=99,null=True)
    DriverSearchConductedBy  = models.CharField(max_length=99,null=True)
    PassengerConsentSearchRequested  = models.CharField(max_length=99,null=True)
    PassengerConsentGiven  = models.CharField(max_length=99,null=True)
    PassengerSearchConducted  = models.CharField(max_length=99,null=True)
    PassengerSearchConductedBy  = models.CharField(max_length=99,null=True)
    DriverPassengerContrabandFound  = models.CharField(max_length=99,null=True)
    DriverPassengerDrugsFound  = models.CharField(max_length=99,null=True)
    DriverPassengerDrugParaphernaliaFound  = models.CharField(max_length=99,null=True)
    DriverPassengerAlcoholFound  = models.CharField(max_length=99,null=True)
    DriverPassengerWeaponFound  = models.CharField(max_length=99,null=True)
    DriverPassengerStolenPropertyFound  = models.CharField(max_length=99,null=True)
    DriverPassengerOtherContrabandFound  = models.CharField(max_length=99,null=True)
    DriverPassengerDrugAmount  = models.CharField(max_length=99,null=True)
    PoliceDogPerformSniffOfVehicle  = models.CharField(max_length=99,null=True)
    PoliceDogAlertIfSniffed  = models.CharField(max_length=99,null=True)
    PoliceDogVehicleSearched  = models.CharField(max_length=99,null=True)
    PoliceDogContrabandFound  = models.CharField(max_length=99,null=True)
    PoliceDogDrugsFound  = models.CharField(max_length=99,null=True)
    PoliceDogDrugParaphernaliaFound  = models.CharField(max_length=99,null=True)
    PoliceDogAlcoholFound  = models.CharField(max_length=99,null=True)
    PoliceDogWeaponFound  = models.CharField(max_length=99,null=True)
    PoliceDogStolenPropertyFound  = models.CharField(max_length=99,null=True)
    PoliceDogOtherContrabandFound  = models.CharField(max_length=99,null=True)
    PoliceDogDrugAmount  = models.CharField(max_length=99,null=True)

'''
class OldStop(models.Model):
    AgencyName = models.CharField(max_length=100,null=True)
    DateOfStop = models.DateField()
    TimeOfStop = models.TimeField()
    Location = models.TextField()
    BeatLocation = models.TextField()
    Gender = models.CharField(max_length=99,)
    Race = models.CharField(max_length=99,)
    ReasonForSearchDrug = models.CharField(max_length=99,)
    ReasonForSearchFitsDescriptionRadio = models.CharField(max_length=99,)
    ReasonForSearchFitsDescriptionWitness = models.CharField(max_length=99,)
    ReasonForSearchCasing = models.CharField(max_length=99,)
    ReasonForSearchProximity = models.CharField(max_length=99,)
    ReasonForSearchGangEnforcement = models.CharField(max_length=99,)
    ReasonForSearchSuspiciousActivity = models.CharField(max_length=99,)
    ReasonForSearchOther = models.CharField(max_length=99,)
    ReasonForSearchSpecifyOther = models.TextField()
    FriskWasConducted = models.CharField(max_length=99,)
    FriskConductedBy = models.CharField(max_length=99,)
    ReasonForFriskVerbalThreats = models.CharField(max_length=99,)
    ReasonForFriskPriorKnowlege = models.CharField(max_length=99,)
    ReasonForFriskViolentActions = models.CharField(max_length=99,) #ReasonForFriskViolentAcitons
    ReasonForFriskViolentCrime = models.CharField(max_length=99,)
    ReasonForFriskSuspisiousBulge = models.CharField(max_length=99,)
    ReasonForFriskEvasive = models.CharField(max_length=99,)
    ReasonForFriskOther = models.CharField(max_length=99,)
    ReasonForFriskSpecifyOther = models.CharField(max_length=100,null=True)
    FriskLedToSearchBeyond = models.CharField(max_length=99,)
    SearchBeyondWasConducted = models.CharField(max_length=99,)
    SearchBeyondConductedBy = models.CharField(max_length=99,)
    ReasonForSearchBeyondDrugParaphernalia = models.CharField(max_length=99,)
    ReasonForSearchBeyondHardObject = models.CharField(max_length=99,)
    ReasonForSearchBeyondFirearm = models.CharField(max_length=99,)
    ReasonForSearchBeyondOtherWeapon = models.CharField(max_length=99,)
    ReasonForSearchBeyondOther = models.CharField(max_length=99,)
    ReasonForSearchBeyondSpecifyOther = models.CharField(max_length=100,null=True)
    SearchBeyondFoundContraband = models.CharField(max_length=99,)
    SearchBeyondFoundDrugs = models.CharField(max_length=99,)
    SearchBeyondFoundDrugParaphernalia = models.CharField(max_length=99,)
    SearchBeyondFoundAlcohol = models.CharField(max_length=99,)
    SearchBeyondFoundWeapon = models.CharField(max_length=99,)
    SearchBeyondFoundStolenProperty = models.CharField(max_length=99,)
    SearchBeyondFoundOther = models.CharField(max_length=99,)
    SearchBeyondAmountOfDrugsFound = models.CharField(max_length=99,)
    WarningCitationIssued = models.CharField(max_length=99,)
    Arrest = models.CharField(max_length=99,)
    ViolationsOrCharges = models.CharField(max_length=100,null=True)


'''



# TODO: model for agencies
