# Generated by Django 4.1 on 2022-12-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgencyCode', models.TextField()),
                ('AgencyName', models.CharField(max_length=100, null=True)),
                ('DateOfStop', models.DateField(null=True)),
                ('TimeOfStop', models.TimeField(null=True)),
                ('DurationOfStop', models.CharField(max_length=99, null=True)),
                ('zipcode', models.CharField(max_length=100, null=True)),
                ('VehicleMake', models.TextField(null=True)),
                ('VehicleYear', models.CharField(max_length=99, null=True)),
                ('DriversYearofBirth', models.CharField(max_length=99, null=True)),
                ('DriverSex', models.CharField(max_length=99, null=True)),
                ('DriverRace', models.CharField(max_length=99, null=True)),
                ('ReasonForStop', models.CharField(max_length=99, null=True)),
                ('TypeOfMovingViolation', models.CharField(max_length=10, null=True)),
                ('ResultOfStop', models.CharField(max_length=99, null=True)),
                ('BeatLocationOfStop', models.TextField(null=True)),
                ('VehicleConsentSearchRequested', models.CharField(max_length=99, null=True)),
                ('VehicleConsentGiven', models.CharField(max_length=99, null=True)),
                ('VehicleSearchConducted', models.CharField(max_length=99, null=True)),
                ('VehicleSearchConductedBy', models.CharField(max_length=99, null=True)),
                ('VehicleContrabandFound', models.CharField(max_length=99, null=True)),
                ('VehicleDrugsFound', models.CharField(max_length=99, null=True)),
                ('VehicleDrugParaphernaliaFound', models.CharField(max_length=99, null=True)),
                ('VehicleAlcoholFound', models.CharField(max_length=99, null=True)),
                ('VehicleWeaponFound', models.CharField(max_length=99, null=True)),
                ('VehicleStolenPropertyFound', models.CharField(max_length=99, null=True)),
                ('VehicleOtherContrabandFound', models.CharField(max_length=99, null=True)),
                ('VehicleDrugAmount', models.CharField(max_length=99, null=True)),
                ('DriverConsentSearchRequested', models.CharField(max_length=99, null=True)),
                ('DriverConsentGiven', models.CharField(max_length=99, null=True)),
                ('DriverSearchConducted', models.CharField(max_length=99, null=True)),
                ('DriverSearchConductedBy', models.CharField(max_length=99, null=True)),
                ('PassengerConsentSearchRequested', models.CharField(max_length=99, null=True)),
                ('PassengerConsentGiven', models.CharField(max_length=99, null=True)),
                ('PassengerSearchConducted', models.CharField(max_length=99, null=True)),
                ('PassengerSearchConductedBy', models.CharField(max_length=99, null=True)),
                ('DriverPassengerContrabandFound', models.CharField(max_length=99, null=True)),
                ('DriverPassengerDrugsFound', models.CharField(max_length=99, null=True)),
                ('DriverPassengerDrugParaphernaliaFound', models.CharField(max_length=99, null=True)),
                ('DriverPassengerAlcoholFound', models.CharField(max_length=99, null=True)),
                ('DriverPassengerWeaponFound', models.CharField(max_length=99, null=True)),
                ('DriverPassengerStolenPropertyFound', models.CharField(max_length=99, null=True)),
                ('DriverPassengerOtherContrabandFound', models.CharField(max_length=99, null=True)),
                ('DriverPassengerDrugAmount', models.CharField(max_length=99, null=True)),
                ('PoliceDogPerformSniffOfVehicle', models.CharField(max_length=99, null=True)),
                ('PoliceDogAlertIfSniffed', models.CharField(max_length=99, null=True)),
                ('PoliceDogVehicleSearched', models.CharField(max_length=99, null=True)),
                ('PoliceDogContrabandFound', models.CharField(max_length=99, null=True)),
                ('PoliceDogDrugsFound', models.CharField(max_length=99, null=True)),
                ('PoliceDogDrugParaphernaliaFound', models.CharField(max_length=99, null=True)),
                ('PoliceDogAlcoholFound', models.CharField(max_length=99, null=True)),
                ('PoliceDogWeaponFound', models.CharField(max_length=99, null=True)),
                ('PoliceDogStolenPropertyFound', models.CharField(max_length=99, null=True)),
                ('PoliceDogOtherContrabandFound', models.CharField(max_length=99, null=True)),
                ('PoliceDogDrugAmount', models.CharField(max_length=99, null=True)),
            ],
        ),
    ]
