# Generated by Django 4.1 on 2022-09-01 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0001_initial'),
    ]

    operations = [
    ]
