# Generated by Django 4.1 on 2023-02-11 16:59
from django.db import migrations
from stops.models import Stop
import os, csv, datetime, dateparser, ipdb
from traffic_stops.settings import BASE_DIR, LOADER_DEBUG
from stops.utils.loaders import convert_date, convert_time, \
        convert_int, get_year, convert_time_ampm


### START CONFIG ###
data_dir = str(BASE_DIR) + '/data/'
data_filenames = ['2006 Raw Data Statewide.txt',
        '2005 Raw Data Statewide.txt',
        '2004 Raw Data Statewide.txt',
        ]
### END CONFIG ###


def load_files(apps,schema_editor):
    # load each file one at a time
    for filename in data_filenames:
        print('loading',filename)
        file_path = data_dir + filename 
        year = filename[0:4]
        # convert to csv
        data_file = open(file_path,encoding='latin-1') #TODO verify this encoding
        data_csv = csv.DictReader(data_file,delimiter='~')
        try:
            load_data(data_csv,year)
        except Exception as e:
            print(e)
            import ipdb; ipdb.set_trace()


def load_data(data_csv,year):
    # keep track of each stop
    stop_objs = []
    counter = 1

    # handle inconsistent field names
    agency_row_name = 'AgencyName' if 'AgencyName' in data_csv.fieldnames else 'Agency Name'
    zipcode_row_name = 'ZIPCode' if 'ZIPCode' in data_csv.fieldnames else 'ZIP'
    driver_yob_row_name = 'DriversYearofBirth' if 'DriversYearofBirth' in data_csv.fieldnames else 'DriverYearofBirth'
   
    #header_assignments = header_assignments()

    for row in data_csv:
        row_date = row['DateAndTimeOfStop'].split()[0]
        row_date_formatted = convert_date(row_date)
        row_time = ' '.join(row['DateAndTimeOfStop'].split()[1:])
        row_time_formatted = convert_time_ampm(row_time,counter)
        pk = int(year + str(counter))
        
        # cleanup
        for key in row:
            if row[key] in ('#REF!',''):
                row[key] = None
            # convert ints to int or none
            if key in ['VehicleYear']:
                row[key] = convert_int(row[key],counter)


        try:
            stop_obj = Stop(
                        pk = pk,
                        AgencyName = row['AgencyName'],
                        AgencyCode = row['AgencyCode'],
                        year = get_year(row_date_formatted),
                        #DateOfStop = row_date_formatted,
                        #TimeOfStop = row_time_formatted,
                        DateOfStop = row_date,
                        TimeOfStop = row_time,
                        VehicleMake = row['VehicleMake'],
                        VehicleYear = row['VehicleYear'],
                        DriversYearofBirth = row['DriverYearOfBirth'],
                        DriverSex = row['DriverSex'],
                        DriverRace = row['Race'],
                        ReasonForStop = row['ReasonForStop'],
                        TypeOfMovingViolation = row['MovingViolationType'],
                        ResultOfStop = row['ResultOfStop'],
                        TypeOfRoadway = row['TypeOfRoadway'],
                        BeatLocationOfStop = row['BeatLocationOfStop'],
                        SearchConducted = row['SearchConducted'],
                        VehicleSearchType = row['VehicleSearchType'],
                        DriverSearchType = row['DriverSearchType'],
                        Passenger1SearchType = row['Passenger1SearchType'],
                        Passenger2SearchType = row['Passenger2SearchType'],
                        Passenger3SearchType = row['Passenger3SearchType'],
                        Passenger4SearchType = row['Passenger4SearchType'],
                        Passenger5SearchType = row['Passenger5SearchType'],
                        Passenger6SearchType = row['Passenger6SearchType'],
                        ContrabandFound = row['ContrabandFound'],
                        DrugsFound = row['DrugsFound'],
                        WeaponFound = row['WeaponFound'],
                        StolenPropertyFound = row['StolenPropertyFound'],
                        OtherContrabandFound = row['OtherContrabandFound'],
                )
            stop_objs.append(stop_obj)

        except Exception as e:
            print('pk:',pk)
            print('error:',e)
            #ipdb.set_trace()

        counter += 1
        if LOADER_DEBUG:
            if counter > 10:
                break


    Stop.objects.bulk_create(stop_objs)

class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0003_load_2007_2011_stops'),
    ]

    operations = [
        migrations.RunPython(load_files)
    ]
