# Generated by Django 4.1 on 2023-05-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0006_load_2019_2021_cpd_stops'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='consent_search_conducted',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='consent_search_requested',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='dog_search_conducted',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='dog_search_hit',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='dog_sniff',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='driver_race',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='outcome',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='search_conducted',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='search_hit',
            field=models.BooleanField(null=True),
        ),
    ]
