# Generated by Django 4.1 on 2023-05-26 21:42
from django.db import migrations, connection
from stops.models import Stop, Agency

# db
cursor = connection.cursor()

def create_agencies(apps,schema_editor):
    """
    create agencies 
    using distinct agency code
    and corresponding agency name
    """
    # use codes as primary IDs
    agency_codes = Stop.objects.values('AgencyCode').distinct()

    # loop thru and create
    for agency_obj in agency_codes:
        # get code from the db obj
        agency_code = agency_obj['AgencyCode']
        print(agency_code)
        # look up name by id
        results = cursor.execute("select distinct AgencyName from stops where AgencyCode = '" + agency_code + "'")
        # there may be multiple naming conventions, get the most recent
        agency_name = results[-1][0]
        print('creating',agency_name)
        agency = Agency.objects.create(name=agency_name,code=agency_code)
        agency.save()


        

def link_agencies(apps,schema_editor):
    """
    for each agency,
    get all stops
    bulk update stop.agency
    """
    for agency in Agency.objects.all():
        print('bulk updating stops for',agency.name)
        stops = Stop.objects.filter(AgencyCode=agency.code)
        stops.update(agency=agency)

class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0007_summary_fields'),
    ]

    operations = [
            migrations.RunPython(create_agencies),
            migrations.RunPython(link_agencies)
    ]
