# Generated by Django 4.1 on 2023-06-01 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0008_create_agencies'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=99)),
                ('year', models.CharField(max_length=20, null=True)),
                ('metric', models.CharField(max_length=99)),
                ('value', models.CharField(max_length=99, null=True)),
                ('rank', models.IntegerField(null=True)),
                ('notes', models.CharField(max_length=99, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stops.agency')),
            ],
            options={
                'db_table': 'agency_data',
            },
        ),
    ]
