# Generated by Django 4.1 on 2023-06-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0009_agencydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='aian_h',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='aian_nh',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='asian_h',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='asian_nh',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='black_h',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='black_nh',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='other_h',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='other_nh',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='total_pop',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='two_or_more_h',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='two_or_more_nh',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='white_h',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='white_nh',
            field=models.IntegerField(null=True),
        ),
    ]
