# Generated by Django 4.1 on 2023-06-13 19:38

from django.db import migrations
from traffic_stops.settings import BASE_DIR
import csv
from stops.models import Agency

### START CONFIG ###
data_dir = str(BASE_DIR) + '/data/'
census_place_path = data_dir + 'www2.census.gov_geo_docs_reference_codes2020_place_st17_il_place2020.txt'
census_county_path = data_dir + 'www2.census.gov_geo_docs_reference_codes2020_cou_st17_il_cou2020.txt'
### END CONFIG ###

def load_geoids(apps,schema_editor):
    """
    assign geoids based on codes from u.s. census
    """
    # get census data
    census_places = [x for x in csv.DictReader(open(census_place_path),delimiter='|')]
    census_counties = [x for x in csv.DictReader(open(census_county_path),delimiter='|')]



    # roll through agencies
    for agency in Agency.objects.all():
        # municipal police
        if 'POLICE' in agency.name:
            agency_name_formatted = agency.name.upper().replace(' POLICE','')
            for place in census_places:
                place_name_formatted = place['PLACENAME'].replace(' city','').replace(' village','').upper()
                if agency_name_formatted == place_name_formatted:
                    print('matching', agency.name, place['PLACENAME'])
                    agency.geoid = place['STATEFP'] + place['PLACEFP']
                    agency.save()

        # sheriffs
        if 'SHERIFF' in agency.name:
            agency_name_formatted = agency.name.upper().replace(' SHERIFF','').replace(" SHERIFF'S OFFICE",'')
            for place in census_counties:
                place_name_formatted = place['COUNTYNAME'].upper()
                if agency_name_formatted == place_name_formatted:
                    print('matching', agency.name, place['COUNTYNAME'])
                    agency.geoid = place['STATEFP'] + place['COUNTYFP']
                    agency.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0010_census_metadata'),
    ]

    operations = [
            migrations.RunPython(load_geoids)
    ]
