# Generated by Django 4.1 on 2023-06-15 23:35

import csv
from django.db import migrations
from traffic_stops.settings import data_dir
from stops.models import Agency

### START CONFIG ###
places_b03002_path = data_dir + 'acs2021_5yr_B03002_16000US1743445.csv'
counties_b03002_path = data_dir + 'acs2021_5yr_B03002_16000US1743445_counties.csv'
### END CONFIG ###

agencies = Agency.objects.all()

def load_data(apps,schema_editor):
    """
    load places and county tables
    """
    load_place_county_data()


def load_place_county_data():
    """
    load place b030002 data from file
    """
    # load datas
    place_data = [x for x in csv.DictReader(open(places_b03002_path))]
    county_data = [x for x in csv.DictReader(open(counties_b03002_path))]
    
    # loop thru combined lists
    for pc in place_data + county_data:
        # strip geoid to last 5-7 chars
        geoid = pc['geoid'][7:]
        # look up agency matching on geoid
        agency = [x for x in agencies if x.geoid == geoid]
        # check if you found one
        if agency:
            # ... if so, it's the first one in the list
            agency = agency[0]
            # start assigning data to db attrs
            agency.total_pop = pc['B03002001']
            agency.white_nh = pc['B03002003']
            agency.black_nh = pc['B03002004']
            agency.aian_nh = pc['B03002005']
            agency.asian_nh = pc['B03002006']
            # TODO insert Native Hawaiian/PI
            # agency.nhpi = pc['B03002007']
            agency.other_nh = pc['B03002008']
            agency.two_or_more_nh = pc['B03002009']
            agency.white_h = pc['B03002013']
            agency.black_h = pc['B03002014']
            agency.aian_h = pc['B03002015']
            agency.asian_h = pc['B03002016']
            # TODO insert Native Hawaiian/PI
            # agency.nhpi = pc['B03002017']
            agency.other_h = pc['B03002018']
            agency.two_or_more_h = pc['B03002019']
            # print
            print('assigning attrs for',pc['name'],'to',agency.name)
            # save
            agency.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0011_add_census_geoids'),
    ]

    operations = [
            migrations.RunPython(load_data)
    ]
