# Generated by Django 4.1 on 2023-08-22 19:20
import json, csv
from stops.models import Agency, AgencyData, table_codes
from django.db import migrations
from traffic_stops.settings import data_dir

#* SOURCE *#
# census reporter
# https://censusreporter.org/data/table/?table=B01001B&geo_ids=160|04000US17,050|04000US17&primary_geo_id=04000US17

### START CONFIG ###
table_prefix = 'acs2021_5yr_'
table_name = 'B01001'
table_suffix = '_16000US1740364'
### END CONFIG ###



def update(apps,schema_editor):
    # loop through each racial group
    for race in table_codes:
        # get the single-letter code
        code = table_codes[race]
        # full table name
        full_table_name = table_prefix + table_name + code + table_suffix
        # each census file is in the data folder
        file_dir = data_dir + full_table_name + '/'
        # file is nested within the folder
        file_path = file_dir + full_table_name + '.csv'
        # metadata 
        metadata_path = file_dir + 'metadata.json'
        metadata = json.load(open(metadata_path))
        meta = metadata['tables'][table_name + code]
        title = meta['title']
        universe = meta['universe']
        # loop thru cols to add agency data points
        columns = meta['columns']
        # open as csv
        file_csv = [x for x in csv.DictReader(open(file_path))]
        # places and counties
        for place in file_csv:
            # get geoid from csv row
            geoid = place['geoid'].split('US')[-1]
            # use that geoid to look up agency
            agencies = Agency.objects.filter(geoid=geoid)
            if len(agencies) == 1:
                agency = agencies[0]
                #print('match',agency.name)
            else:
                continue
                pass#print('no clear match for', place['name'], place['geoid'], len(agencies))
            # loop through columns to add data points
            print(place['name'],geoid,agency.name)
            for field in columns:
                # male or female depending on field name -- bad hack
                field_no = int(field.split(code)[-1])
                mf = ''
                mf = 'male' if field_no > 2 and field_no < 17 else mf
                mf = 'female' if field_no > 17 else mf
                field_data = place[field]
                field_name = meta['columns'][field]['name']
                # create agencydata w/ that agency
                ad = AgencyData.objects.create(
                        agency = agency,
                        agency_name = agency.name,
                        year = 2021,
                        metric = field,
                        value = field_data,
                        notes = ' ~ '.join([title,universe,field_name,mf])
                        )
                ad.save()

class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0015_summary_fields_update'),
    ]

    operations = [
            migrations.RunPython(update)
    ]
