# Generated by Django 4.1 on 2023-09-19 19:06

from django.db import migrations, models

"""
ran this query to null old values from migration 0012
update agencies set aian_nh = null, white_nh = null, latino = null, nhpi_nh = null , other = null, two_or_more = null, asian_nh = null, black_nh = null, total_pop = null;
"""


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0016_census_race_by_age_agency_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='aian_h',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='asian_h',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='black_h',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='other_h',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='other_nh',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='two_or_more_h',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='two_or_more_nh',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='white_h',
        ),
        migrations.AddField(
            model_name='agency',
            name='latino',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='nhpi_nh',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='other',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='two_or_more',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='agencydata',
            name='notes',
            field=models.CharField(max_length=99),
        ),
    ]
