# Generated by Django 4.1 on 2023-06-15 23:35

import csv
from django.db import migrations
from traffic_stops.settings import data_dir
from stops.models import Agency

### START CONFIG ###
place_county_data_path = data_dir + 'agency_place_county_2020_census_population.csv'
### END CONFIG ###

agencies = Agency.objects.all()

def load_data(apps,schema_editor):
    """
    load Alden's census data from file (see #proj-traffic-stops 2023-9-10)
    """
    # converted to csv
    place_county_data = [x for x in csv.DictReader(open(place_county_data_path))]
    
    # loop thru combined lists
    for pc in place_county_data:
        # strip geoid to last 5-7 chars
        geoid = pc['geoid']
        # look up agency matching on geoid
        agency = [x for x in agencies if x.geoid == geoid]
        # check if you found one
        if agency:
            # ... if so, it's the first one in the list
            agency = agency[0]
            # start assigning data to db attrs
            agency.total_pop = pc['Total']
            agency.latino = pc['Latino']
            agency.white_nh = pc['White']
            agency.black_nh = pc['Black']
            agency.aian_nh = pc['AIAN']
            agency.asian_nh = pc['Asian']
            agency.nhpi_nh = pc['NHPI']
            agency.other_nh = pc['Other']
            agency.two_or_more_nh = pc['TOM']
            # print
            print('assigning attrs for',pc['name'],'to',agency.name)
            # save
            agency.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0017_remove_agency_aian_h_remove_agency_asian_h_and_more'),
    ]

    operations = [
            migrations.RunPython(load_data)
    ]
