# Generated by Django 4.1 on 2023-11-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0017_remove_agency_aian_h_remove_agency_asian_h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='census_name',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='name_cased',
            field=models.CharField(max_length=99, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='regions',
            field=models.CharField(max_length=99, null=True),
        ),
    ]
