# Generated by Django 4.1 on 2023-06-15 23:35

import csv
from django.db import migrations
from traffic_stops.settings import data_dir
from stops.models import Agency

### START CONFIG ###
place_county_data_path = data_dir + 'agency_place_county_2020_census_population.csv'
place_county_no_geoids_data_path = data_dir + 'agency_place_county_2020_census_population_no_geoid.csv'
### END CONFIG ###

agencies = Agency.objects.all()

def load_data(apps,schema_editor):
    """
    load Alden's census data from files (see #proj-traffic-stops 2023-9-10)
    """
    # there were two files: one with Matt-provided geoids ... 
    place_county_data = [x for x in csv.DictReader(open(place_county_data_path))]
    # ... plus another file where Alden added some geoids
    place_county_data += [x for x in csv.DictReader(open(place_county_no_geoids_data_path))]
    
    # loop thru combined lists
    for pc in place_county_data:
        # geoid = pc['geoid']
        # actually let's go with names because geoids are sometimes omitted
        name = pc['name']
        # look up agency matching on geoid
        agency = [x for x in agencies if x.name == name]
        # check if you found one and if there's data
        if agency and pc['Total']:
            # ... if so, it's the first one in the list
            agency = agency[0]
            # start assigning data to db attrs
            agency.total_pop = pc['Total']
            agency.latino = pc['Latino']
            agency.white_nh = pc['White']
            agency.black_nh = pc['Black']
            agency.aian_nh = pc['AIAN']
            agency.asian_nh = pc['Asian']
            agency.nhpi_nh = pc['NHPI']
            agency.other = pc['Other']
            agency.two_or_more = pc['TOM']
            # census name
            agency.census_name = pc['BASENAME']
            # print
            print('assigning attrs for',pc['name'],'to',agency.name,' - census name',agency.census_name)
            # save
            agency.save()


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0018_agency_census_name_agency_name_cased'),
    ]

    operations = [
            migrations.RunPython(load_data)
    ]
