# Generated by Django 4.1 on 2023-12-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0020_add_cased_census_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='public_drive_id',
            field=models.CharField(max_length=99, null=True),
        ),
    ]
