# Generated by Django 4.1 on 2024-07-09 01:11

from django.db import migrations
from stops.models import Stop

def update(apps,schema_editor):
    counter = 0
    stops23 = Stop.objects.filter(year=2023)
    for stop in stops23:
        stop.save()
        counter+=1
        if counter % 100000 == 0:
            print(counter)


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0025_load_2023_cpd'),
    ]

    operations = [
            migrations.RunPython(update)
    ]
